//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyaseer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsManager { get; set; }
        public bool Access_Users { get; set; }
        public bool Access_Products { get; set; }
        public bool Access_Categories { get; set; }
        public bool Access_Contacts { get; set; }
        public bool Access_Orders { get; set; }
        public bool Access_Providers { get; set; }
        public bool Access_Codes { get; set; }
    }
}
