//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyaseer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Code> Codes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product_Data> Product_Data { get; set; }
        public virtual DbSet<Product_NotAvaiableDates> Product_NotAvaiableDates { get; set; }
        public virtual DbSet<Product_Photos> Product_Photos { get; set; }
        public virtual DbSet<Product_Rates> Product_Rates { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Provider_Rates> Provider_Rates { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Product_Types> Product_Types { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<EmailVerify> EmailVerifies { get; set; }
    
        public virtual int EditProviderFCM(Nullable<int> provider_id, string fcm)
        {
            var provider_idParameter = provider_id.HasValue ?
                new ObjectParameter("provider_id", provider_id) :
                new ObjectParameter("provider_id", typeof(int));
    
            var fcmParameter = fcm != null ?
                new ObjectParameter("fcm", fcm) :
                new ObjectParameter("fcm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditProviderFCM", provider_idParameter, fcmParameter);
        }
    
        public virtual int EditUserFCM(Nullable<int> user_id, string fcm)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var fcmParameter = fcm != null ?
                new ObjectParameter("fcm", fcm) :
                new ObjectParameter("fcm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditUserFCM", user_idParameter, fcmParameter);
        }
    }
}
