//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyaseer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Rates
    {
        public int ID { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Comment { get; set; }
        public int Provider_ID { get; set; }
        public int User_ID { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual User User { get; set; }
    }
}
